/*
 * Murdock API
 *
 * This is the Murdock API
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct ManualJobBranchParamModel {
    #[serde(rename = "env", skip_serializing_if = "Option::is_none")]
    pub env: Option<serde_json::Value>,
    #[serde(rename = "fasttrack", skip_serializing_if = "Option::is_none")]
    pub fasttrack: Option<bool>,
    #[serde(rename = "branch")]
    pub branch: String,
}

impl ManualJobBranchParamModel {
    pub fn new(branch: String) -> ManualJobBranchParamModel {
        ManualJobBranchParamModel {
            env: None,
            fasttrack: None,
            branch,
        }
    }
}


