/*
 * Murdock API
 *
 * This is the Murdock API
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct PullRequestInfo {
    #[serde(rename = "title", skip_serializing_if = "Option::is_none")]
    pub title: Option<String>,
    #[serde(rename = "number", skip_serializing_if = "Option::is_none")]
    pub number: Option<i32>,
    #[serde(rename = "merge_commit", skip_serializing_if = "Option::is_none")]
    pub merge_commit: Option<String>,
    #[serde(rename = "user", skip_serializing_if = "Option::is_none")]
    pub user: Option<String>,
    #[serde(rename = "url", skip_serializing_if = "Option::is_none")]
    pub url: Option<String>,
    #[serde(rename = "base_repo", skip_serializing_if = "Option::is_none")]
    pub base_repo: Option<String>,
    #[serde(rename = "base_branch", skip_serializing_if = "Option::is_none")]
    pub base_branch: Option<String>,
    #[serde(rename = "base_commit", skip_serializing_if = "Option::is_none")]
    pub base_commit: Option<String>,
    #[serde(rename = "base_full_name", skip_serializing_if = "Option::is_none")]
    pub base_full_name: Option<String>,
    #[serde(rename = "mergeable", skip_serializing_if = "Option::is_none")]
    pub mergeable: Option<bool>,
    #[serde(rename = "labels", skip_serializing_if = "Option::is_none")]
    pub labels: Option<Vec<String>>,
    #[serde(rename = "state", skip_serializing_if = "Option::is_none")]
    pub state: Option<String>,
    #[serde(rename = "is_merged", skip_serializing_if = "Option::is_none")]
    pub is_merged: Option<bool>,
}

impl PullRequestInfo {
    pub fn new() -> PullRequestInfo {
        PullRequestInfo {
            title: None,
            number: None,
            merge_commit: None,
            user: None,
            url: None,
            base_repo: None,
            base_branch: None,
            base_commit: None,
            base_full_name: None,
            mergeable: None,
            labels: None,
            state: None,
            is_merged: None,
        }
    }
}


