/*
 * Murdock API
 *
 * This is the Murdock API
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct ValidationError {
    #[serde(rename = "loc")]
    pub loc: Vec<crate::models::LocationInner>,
    #[serde(rename = "msg")]
    pub msg: String,
    #[serde(rename = "type")]
    pub _type: String,
}

impl ValidationError {
    pub fn new(loc: Vec<crate::models::LocationInner>, msg: String, _type: String) -> ValidationError {
        ValidationError {
            loc,
            msg,
            _type,
        }
    }
}


