/*
 * Murdock API
 *
 * This is the Murdock API
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct ManualJobCommitParamModel {
    #[serde(rename = "env", skip_serializing_if = "Option::is_none")]
    pub env: Option<serde_json::Value>,
    #[serde(rename = "fasttrack", skip_serializing_if = "Option::is_none")]
    pub fasttrack: Option<bool>,
    #[serde(rename = "sha")]
    pub sha: String,
}

impl ManualJobCommitParamModel {
    pub fn new(sha: String) -> ManualJobCommitParamModel {
        ManualJobCommitParamModel {
            env: None,
            fasttrack: None,
            sha,
        }
    }
}


